# Generated by Django 5.1.6 on 2025-03-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='speciality',
            field=models.CharField(blank=True, choices=[('GP', 'General Practitioner'), ('DENT', 'Dentist'), ('CARD', 'Cardiologist'), ('OPTH', 'Ophthalmologist'), ('ENT', 'ENT Specialist'), ('ORTHO', 'Orthopedic'), ('NEURO', 'Neurologist'), ('DERM', 'Dermatologist'), ('PEDIA', 'Pediatrician'), ('PSYCH', 'Psychiatrist'), ('ONC', 'Oncologist')], max_length=20, null=True),
        ),
    ]
