# Generated by Django 5.1.6 on 2025-03-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_calendar_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
