# Generated by Django 5.1.6 on 2025-03-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_google_calendar_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_calendar_credentials',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
